_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/yolox_reader.yml'
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 10
weights: output/yolox_s_300e_coco/model_final


TrainReader:
  batch_size: 16

EvalReader:
  batch_size: 16

LearningRate:
  base_lr: 0.01   # 0.01 for total batch_size==64; 0.02 for total batch_size==128;
  schedulers:
  - !CosineDecay
    max_epochs: 300
    min_lr_ratio: 0.05
    last_plateau_epochs: 15
  - !ExpWarmup
    epochs: 5

