_BASE_: [
  '../datasets/voc2012_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_80e.yml',
  './_base_/ppyoloe_plus_crn.yml',
  './_base_/ppyoloe_plus_reader.yml',
]

log_iter: 20
snapshot_epoch: 2
weights: output/ppyoloe_plus_crn_s_16e_voc2012/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_s_80e_coco.pdparams
depth_mult: 0.33
width_mult: 0.50

epoch: 16

LearningRate:
  base_lr: 0.00025  # bs=16
  schedulers:
    - name: CosineDecay
      max_epochs: 20
    - name: LinearWarmup
      start_factor: 0.
      epochs: 1

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2


PPYOLOEHead:
  static_assigner_epoch: 4

TrainReader:
  batch_size: 16

EvalReader:
  batch_size: 8


