metric: COCO
num_classes: 20

TrainDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: annotations2/voc2012_train.json
  dataset_dir: ../VOCdevkit/VOC2012
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: annotations2/voc2012_val.json
  dataset_dir: ../VOCdevkit/VOC2012
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations2/voc2012_val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: ../VOCdevkit/VOC2012 # if set, anno_path will be 'dataset_dir/anno_path'
